IMPORT Numpy and Pandas

In [27]:
import numpy as np

In [28]:
import pandas as pd

In [29]:
#loading data from csv files

In [30]:
data_loader1 = pd.DataFrame(pd.read_csv('bank-full-1540270465813.csv', ';'))
data_loader2 = pd.DataFrame(pd.read_csv('datasets_90770_209752_insurance.csv', ','))
data_loader3 = pd.DataFrame(pd.read_csv('./96967_226958_bundle_archive/insurance_claims.csv', ','))
data_loader4 = pd.DataFrame(pd.read_csv('./96967_226958_bundle_archive/insurance_data_set.csv', ','))

In [31]:
#print all the data sets

In [32]:
print(data_loader1)
print(data_loader2)
print(data_loader3)
print(data_loader4)

       age            job   marital  education default  balance housing loan  \
0       58     management   married   tertiary      no     2143     yes   no
1       44     technician    single  secondary      no       29     yes   no
2       33   entrepreneur   married  secondary      no        2     yes  yes
3       47    blue-collar   married    unknown      no     1506     yes   no
4       33        unknown    single    unknown      no        1      no   no
5       35     management   married   tertiary      no      231     yes   no
6       28     management    single   tertiary      no      447     yes  yes
7       42   entrepreneur  divorced   tertiary     yes        2     yes   no
8       58        retired   married    primary      no      121     yes   no
9       43     technician    single  secondary      no      593     yes   no
10      41         admin.  divorced  secondary      no      270     yes   no
11      29         admin.    single  secondary      no      390     yes   no
12      53     technician   married  secondary      no        6     yes   no
13      58     technician   married    unknown      no       71     yes   no
14      57       services   married  secondary      no      162     yes   no
15      51        retired   married    primary      no      229     yes   no
16      45         admin.    single    unknown      no       13     yes   no
17      57    blue-collar   married    primary      no       52     yes   no
18      60        retired   married    primary      no       60     yes   no
19      33       services   married  secondary      no        0     yes   no
20      28    blue-collar   married  secondary      no      723     yes  yes
21      56     management   married   tertiary      no      779     yes   no
22      32    blue-collar    single    primary      no       23     yes  yes
23      25       services   married  secondary      no       50     yes   no
24      40        retired   married    primary      no        0     yes  yes
25      44         admin.   married  secondary      no     -372     yes   no
26      39     management    single   tertiary      no      255     yes   no
27      52   entrepreneur   married  secondary      no      113     yes  yes
28      46     management    single  secondary      no     -246     yes   no
29      36     technician    single  secondary      no      265     yes  yes
...    ...            ...       ...        ...     ...      ...     ...  ...
45181   46    blue-collar   married  secondary      no     6879      no   no
45182   34     technician   married  secondary      no      133      no   no
45183   70        retired   married    primary      no      324      no   no
45184   63        retired   married  secondary      no     1495      no   no
45185   60       services   married   tertiary      no     4256     yes   no
45186   59        unknown   married    unknown      no     1500      no   no
45187   32       services    single  secondary      no     1168     yes   no
45188   29     management    single  secondary      no      703     yes   no
45189   25       services    single  secondary      no      199      no   no
45190   32    blue-collar   married  secondary      no      136      no   no
45191   75        retired  divorced   tertiary      no     3810     yes   no
45192   29     management    single   tertiary      no      765      no   no
45193   28  self-employed    single   tertiary      no      159      no   no
45194   59     management   married   tertiary      no      138     yes  yes
45195   68        retired   married  secondary      no     1146      no   no
45196   25        student    single  secondary      no      358      no   no
45197   36     management    single  secondary      no     1511     yes   no
45198   37     management   married   tertiary      no     1428      no   no
45199   34    blue-collar    single  secondary      no     1475     yes   no
45200   38     technician   married  secondary      no      557     yes   no
45201   53     management   married   tertiary      no      583      no   no
45202   34         admin.    single  secondary      no      557      no   no
45203   23        student    single   tertiary      no      113      no   no
45204   73        retired   married  secondary      no     2850      no   no
45205   25     technician    single  secondary      no      505      no  yes
45206   51     technician   married   tertiary      no      825      no   no
45207   71        retired  divorced    primary      no     1729      no   no
45208   72        retired   married  secondary      no     5715      no   no
45209   57    blue-collar   married  secondary      no      668      no   no
45210   37   entrepreneur   married  secondary      no     2971      no   no

         contact  day month  duration  campaign  pdays  previous poutcome    y
0        unknown    5   may       261         1     -1         0  unknown   no
1        unknown    5   may       151         1     -1         0  unknown   no
2        unknown    5   may        76         1     -1         0  unknown   no
3        unknown    5   may        92         1     -1         0  unknown   no
4        unknown    5   may       198         1     -1         0  unknown   no
5        unknown    5   may       139         1     -1         0  unknown   no
6        unknown    5   may       217         1     -1         0  unknown   no
7        unknown    5   may       380         1     -1         0  unknown   no
8        unknown    5   may        50         1     -1         0  unknown   no
9        unknown    5   may        55         1     -1         0  unknown   no
10       unknown    5   may       222         1     -1         0  unknown   no
11       unknown    5   may       137         1     -1         0  unknown   no
12       unknown    5   may       517         1     -1         0  unknown   no
13       unknown    5   may        71         1     -1         0  unknown   no
14       unknown    5   may       174         1     -1         0  unknown   no
15       unknown    5   may       353         1     -1         0  unknown   no
16       unknown    5   may        98         1     -1         0  unknown   no
17       unknown    5   may        38         1     -1         0  unknown   no
18       unknown    5   may       219         1     -1         0  unknown   no
19       unknown    5   may        54         1     -1         0  unknown   no
20       unknown    5   may       262         1     -1         0  unknown   no
21       unknown    5   may       164         1     -1         0  unknown   no
22       unknown    5   may       160         1     -1         0  unknown   no
23       unknown    5   may       342         1     -1         0  unknown   no
24       unknown    5   may       181         1     -1         0  unknown   no
25       unknown    5   may       172         1     -1         0  unknown   no
26       unknown    5   may       296         1     -1         0  unknown   no
27       unknown    5   may       127         1     -1         0  unknown   no
28       unknown    5   may       255         2     -1         0  unknown   no
29       unknown    5   may       348         1     -1         0  unknown   no
...          ...  ...   ...       ...       ...    ...       ...      ...  ...
45181   cellular   15   nov        74         2    118         3  failure   no
45182   cellular   15   nov       401         2    187         5  success  yes
45183   cellular   15   nov        78         1     96         7  success   no
45184   cellular   16   nov       138         1     22         5  success   no
45185   cellular   16   nov       200         1     92         4  success  yes
45186   cellular   16   nov       280         1    104         2  failure   no
45187   cellular   16   nov       411         1     -1         0  unknown  yes
45188   cellular   16   nov       236         1    550         2  success  yes
45189   cellular   16   nov       173         1     92         5  failure   no
45190   cellular   16   nov       206         1    188         3  success  yes
45191   cellular   16   nov       262         1    183         1  failure  yes
45192   cellular   16   nov       238         1     -1         0  unknown  yes
45193   cellular   16   nov       449         2     33         4  success  yes
45194   cellular   16   nov       162         2    187         5  failure   no
45195   cellular   16   nov       212         1    187         6  success  yes
45196   cellular   16   nov       330         1     -1         0  unknown  yes
45197   cellular   16   nov       270         1     -1         0  unknown  yes
45198   cellular   16   nov       333         2     -1         0  unknown   no
45199   cellular   16   nov      1166         3    530        12    other   no
45200   cellular   16   nov      1556         4     -1         0  unknown  yes
45201   cellular   17   nov       226         1    184         4  success  yes
45202   cellular   17   nov       224         1     -1         0  unknown  yes
45203   cellular   17   nov       266         1     -1         0  unknown  yes
45204   cellular   17   nov       300         1     40         8  failure  yes
45205   cellular   17   nov       386         2     -1         0  unknown  yes
45206   cellular   17   nov       977         3     -1         0  unknown  yes
45207   cellular   17   nov       456         2     -1         0  unknown  yes
45208   cellular   17   nov      1127         5    184         3  success  yes
45209  telephone   17   nov       508         4     -1         0  unknown   no
45210   cellular   17   nov       361         2    188        11    other   no

[45211 rows x 17 columns]
      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
5      31  female  25.740         0     no  southeast   3756.62160
6      46  female  33.440         1     no  southeast   8240.58960
7      37  female  27.740         3     no  northwest   7281.50560
8      37    male  29.830         2     no  northeast   6406.41070
9      60  female  25.840         0     no  northwest  28923.13692
10     25    male  26.220         0     no  northeast   2721.32080
11     62  female  26.290         0    yes  southeast  27808.72510
12     23    male  34.400         0     no  southwest   1826.84300
13     56  female  39.820         0     no  southeast  11090.71780
14     27    male  42.130         0    yes  southeast  39611.75770
15     19    male  24.600         1     no  southwest   1837.23700
16     52  female  30.780         1     no  northeast  10797.33620
17     23    male  23.845         0     no  northeast   2395.17155
18     56    male  40.300         0     no  southwest  10602.38500
19     30    male  35.300         0    yes  southwest  36837.46700
20     60  female  36.005         0     no  northeast  13228.84695
21     30  female  32.400         1     no  southwest   4149.73600
22     18    male  34.100         0     no  southeast   1137.01100
23     34  female  31.920         1    yes  northeast  37701.87680
24     37    male  28.025         2     no  northwest   6203.90175
25     59  female  27.720         3     no  southeast  14001.13380
26     63  female  23.085         0     no  northeast  14451.83515
27     55  female  32.775         2     no  northwest  12268.63225
28     23    male  17.385         1     no  northwest   2775.19215
29     31    male  36.300         2    yes  southwest  38711.00000
...   ...     ...     ...       ...    ...        ...          ...
1308   25  female  30.200         0    yes  southwest  33900.65300
1309   41    male  32.200         2     no  southwest   6875.96100
1310   42    male  26.315         1     no  northwest   6940.90985
1311   33  female  26.695         0     no  northwest   4571.41305
1312   34    male  42.900         1     no  southwest   4536.25900
1313   19  female  34.700         2    yes  southwest  36397.57600
1314   30  female  23.655         3    yes  northwest  18765.87545
1315   18    male  28.310         1     no  northeast  11272.33139
1316   19  female  20.600         0     no  southwest   1731.67700
1317   18    male  53.130         0     no  southeast   1163.46270
1318   35    male  39.710         4     no  northeast  19496.71917
1319   39  female  26.315         2     no  northwest   7201.70085
1320   31    male  31.065         3     no  northwest   5425.02335
1321   62    male  26.695         0    yes  northeast  28101.33305
1322   62    male  38.830         0     no  southeast  12981.34570
1323   42  female  40.370         2    yes  southeast  43896.37630
1324   31    male  25.935         1     no  northwest   4239.89265
1325   61    male  33.535         0     no  northeast  13143.33665
1326   42  female  32.870         0     no  northeast   7050.02130
1327   51    male  30.030         1     no  southeast   9377.90470
1328   23  female  24.225         2     no  northeast  22395.74424
1329   52    male  38.600         2     no  southwest  10325.20600
1330   57  female  25.740         2     no  southeast  12629.16560
1331   23  female  33.400         0     no  southwest  10795.93733
1332   52  female  44.700         3     no  southwest  11411.68500
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]
     months_as_customer  age  policy_number policy_bind_date policy_state  \
0                   328   48         521585       2014-10-17           OH
1                   228   42         342868       2006-06-27           IN
2                   134   29         687698       2000-09-06           OH
3                   256   41         227811       1990-05-25           IL
4                   228   44         367455       2014-06-06           IL
5                   256   39         104594       2006-10-12           OH
6                   137   34         413978       2000-06-04           IN
7                   165   37         429027       1990-02-03           IL
8                    27   33         485665       1997-02-05           IL
9                   212   42         636550       2011-07-25           IL
10                  235   42         543610       2002-05-26           OH
11                  447   61         214618       1999-05-29           OH
12                   60   23         842643       1997-11-20           OH
13                  121   34         626808       2012-10-26           OH
14                  180   38         644081       1998-12-28           OH
15                  473   58         892874       1992-10-19           IN
16                   70   26         558938       2005-06-08           OH
17                  140   31         275265       2004-11-15           IN
18                  160   37         921202       2014-12-28           OH
19                  196   39         143972       1992-08-02           IN
20                  460   62         183430       2002-06-25           IN
21                  217   41         431876       2005-11-27           IL
22                  370   55         285496       1994-05-27           IL
23                  413   55         115399       1991-02-08           IN
24                  237   40         736882       1996-02-02           IN
25                    8   35         699044       2013-12-05           OH
26                  257   43         863236       1990-09-20           IN
27                  202   34         608513       2002-07-18           IN
28                  224   40         914088       1990-02-08           OH
29                  241   45         596785       2014-03-04           IL
..                  ...  ...            ...              ...          ...
970                 213   35         844129       1990-09-20           OH
971                  79   25         732169       2000-11-05           OH
972                 232   44         221854       1994-10-03           OH
973                 230   37         776950       2005-04-11           IL
974                 234   41         291006       1990-05-16           IN
975                 240   40         845751       2004-09-11           IN
976                 143   33         889764       1993-11-30           OH
977                 266   42         929306       2003-03-06           IN
978                  89   32         515457       1996-12-18           IN
979                 229   37         556270       1995-02-21           IN
980                 245   40         908935       2009-12-11           IL
981                  50   44         525862       2000-10-18           OH
982                 230   43         490514       2007-02-09           IN
983                  17   39         774895       2006-10-28           IL
984                 163   36         974522       2000-01-27           IN
985                  29   32         669809       2002-04-05           OH
986                 232   42         182953       2013-04-30           IN
987                 235   39         836349       2013-05-01           IL
988                 295   46         591269       1999-01-09           IN
989                  22   21         550127       2007-07-04           IN
990                 286   43         663190       1994-02-05           IL
991                 257   44         109392       2006-07-12           OH
992                  94   26         215278       2007-10-24           IN
993                 124   28         674570       2001-12-08           OH
994                 141   30         681486       2007-03-24           IN
995                   3   38         941851       1991-07-16           OH
996                 285   41         186934       2014-01-05           IL
997                 130   34         918516       2003-02-17           OH
998                 458   62         533940       2011-11-18           IL
999                 456   60         556080       1996-11-11           OH

    policy_csl  policy_deductable  policy_annual_premium  umbrella_limit  \
0      250/500               1000                1406.91               0
1      250/500               2000                1197.22         5000000
2      100/300               2000                1413.14         5000000
3      250/500               2000                1415.74         6000000
4     500/1000               1000                1583.91         6000000
5      250/500               1000                1351.10               0
6      250/500               1000                1333.35               0
7      100/300               1000                1137.03               0
8      100/300                500                1442.99               0
9      100/300                500                1315.68               0
10     100/300                500                1253.12         4000000
11     100/300               2000                1137.16               0
12    500/1000                500                1215.36         3000000
13     100/300               1000                 936.61               0
14     250/500               2000                1301.13               0
15     100/300               2000                1131.40               0
16    500/1000               1000                1199.44         5000000
17    500/1000                500                 708.64         6000000
18    500/1000                500                1374.22               0

I would like to combine two data sets "datasets_90770_209752_insurance" and "insurance_data_set" togather. I think that in business, it is very meaningful to get higher returns at lower costs. From the "insurance_data_set", we can easily get the data distribution of different users purchasing different insurances. First of all, we can use this data set to determine the most profitable group, which is our optimal target customer. Then we can use the distribution in "insurance_claim" to determine the optimal number of target customers in which cities, so that we don’t have to invest the same funds in all cities, but can greatly adjust the proportion of investment to those with high profits area.

In [33]:
# combine these two dataset togather.

In [41]:
r1 = np.concatenate((data_loader2['age'], data_loader3['age']))
r2 = np.concatenate((data_loader2['charges'], data_loader3['policy_annual_premium']))
r3 = np.concatenate((data_loader2['region'], data_loader3['policy_state']))
newdata = pd.DataFrame({'age':r1,'charges':r2,'region':r3})
print(newdata)

      age      charges     region
0      19  16884.92400  southwest
1      18   1725.55230  southeast
2      28   4449.46200  southeast
3      33  21984.47061  northwest
4      32   3866.85520  northwest
5      31   3756.62160  southeast
6      46   8240.58960  southeast
7      37   7281.50560  northwest
8      37   6406.41070  northeast
9      60  28923.13692  northwest
10     25   2721.32080  northeast
11     62  27808.72510  southeast
12     23   1826.84300  southwest
13     56  11090.71780  southeast
14     27  39611.75770  southeast
15     19   1837.23700  southwest
16     52  10797.33620  northeast
17     23   2395.17155  northeast
18     56  10602.38500  southwest
19     30  36837.46700  southwest
20     60  13228.84695  northeast
21     30   4149.73600  southwest
22     18   1137.01100  southeast
23     34  37701.87680  northeast
24     37   6203.90175  northwest
25     59  14001.13380  southeast
26     63  14451.83515  northeast
27     55  12268.63225  northwest
28     23   2775.19215  northwest
29     31  38711.00000  southwest
...   ...          ...        ...
2308   35    871.46000         OH
2309   25   1863.04000         OH
2310   44   1181.64000         OH
2311   37   1060.74000         IL
2312   41    951.56000         IN
2313   40   1533.71000         IN
2314   33   1200.09000         OH
2315   42   1093.83000         IN
2316   32    988.93000         IN
2317   37   1331.94000         IN
2318   40   1361.45000         IL
2319   44   1188.51000         OH
2320   43   1101.83000         IN
2321   39    840.95000         IL
2322   36   1503.21000         IN
2323   32   1722.50000         OH
2324   42    944.03000         IN
2325   39   1453.61000         IL
2326   46   1672.88000         IN
2327   21   1248.05000         IN
2328   43   1564.43000         IL
2329   44   1280.88000         OH
2330   26    722.66000         IN
2331   28   1235.14000         OH
2332   30   1347.04000         IN
2333   38   1310.80000         OH
2334   41   1436.79000         IL
2335   34   1383.49000         OH
2336   62   1356.92000         IL
2337   60    766.19000         OH

[2338 rows x 3 columns]

Write csv file

In [44]:
newdata.to_csv('newdata.csv')